### ISSUE TITLE
Error: The module's source code could not be parsed: Unexpected character

### ISSUE THREAD

**Issue by feresr** [thorwebdev/edgy-edge-functions#9]
The esm.sh link for fetching stripe (https://esm.sh/stripe@11.1.0?target=deno) seems to be returning corrupt (compressed?) data. 
I am getting this error after running `supabase functions deploy`

```
error: Uncaught (in promise) Error: The module's source code could not be parsed: Unexpected character '\u{2}' at https://esm.sh/stripe@11.1.0?target=deno:1:3

  !� F��_��E=�`؀���i�W6ƶ?��N
    ~
      const ret = new Error(getStringFromWasm0(arg0, arg1));
                  ^
```

**Comment by thorwebdev** [comment]
Are you importing this via and import map? You'll need to use an import map for the time being: https://github.com/stripe-samples/stripe-node-deno-samples/issues/2#issuecomment-1346642637

**Comment by feresr** [comment]
I was. The issue was with the CDN. I asked on Discord and they got it fixed. Thank you
